apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dimo-runner-medium-enclave
  namespace: build-runners
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      env: []
      nodeSelector:
        role: worker
        size: medium
        enclave: "true"
      organization: DIMO-Network
      securityContext:
        allowPrivilegeEscalation: true
        privileged: true
      labels:
        - medium
        - enclave
        - ubuntu-latest
      containers:
        - name: runner
          env: []
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: 1800m
              memory: "3Gi"
      volumeMounts:
        - mountPath: /dev/nitro_enclaves
          name: nitro-enclaves
      volumes:
        - name: nitro-enclaves
          hostPath:
            path: /dev/nitro_enclaves
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: dimo-runner-medium-enclave-autoscaler
  namespace: build-runners
spec:
  scaleDownDelaySecondsAfterScaleOut: 600
  scaleTargetRef:
    name: dimo-runner-medium-enclave
  minReplicas: 0
  maxReplicas: 1
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - synthetic-wallet-enclave
